---
language: node_js
node_js:
  - "12"

dist: xenial

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

script:
  - npm test

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
  local-dir: dist
  verbose: true
